
BINARY		= main
# SRCFILES	= main.c vt.c menu.c usbcdc.c blink.c miniprintf.c rtos/heap_4.c rtos/list.c rtos/port.c rtos/queue.c rtos/tasks.c rtos/opencm3.c
SRCFILES	= main.c vt.c usbcdc.c miniprintf.c getline.c rtos/heap_4.c rtos/list.c rtos/port.c rtos/queue.c rtos/tasks.c rtos/opencm3.c

DEVICE 		= stm32f401cc

include ../Makefile.include
include ../Makefile.rtos
